services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ":8000"
    env_file:
      - .env
      - .env.dev
